In [1]:
number = [1,2,3,4,5]

In [2]:
number

[1, 2, 3, 4, 5]

In [9]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
matrix = np.array([
    [1,2],
    [3,4]
])

In [19]:
matrix

array([[1, 2],
       [3, 4]])

In [20]:
arr.shape

(5,)

In [21]:
matrix.shape

(2, 2)

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [23]:
a+b

array([5, 7, 9])

In [24]:
a*2

array([2, 4, 6])

In [25]:
a-b

array([-3, -3, -3])

In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
print(arr)

[1 2 3 4 5]


In [28]:
arr.shape

(5,)

In [29]:
print(arr.shape)

(5,)


In [30]:
print(arr*2)

[ 2  4  6  8 10]


In [31]:
print(arr)

[1 2 3 4 5]


In [32]:
print(arr + 100)

[101 102 103 104 105]


In [33]:
arr

array([1, 2, 3, 4, 5])

In [37]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr.shape)

(4,)


In [38]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

In [40]:
print(arr[0])

10


In [41]:
matrix[0]

array([1, 2, 3])

In [43]:
print(matrix[0][1])

2


In [44]:
print(matrix[0,1])

2


In [45]:
arr = np.array([10,20,30,40,50])

print(arr[1:4])

[20 30 40]


In [46]:
matrix = np.array([
 [1,2,3],
 [4,5,6],
 [7,8,9]
])

In [48]:
matrix[0]

array([1, 2, 3])

In [50]:
matrix[:] # :means-"take everything"

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
matrix[:,0] # all rows,column 0

array([1, 4, 7])

In [51]:
arr = np.array([10,20,30])

In [52]:
arr + 100

array([110, 120, 130])

In [53]:
arr

array([10, 20, 30])

In [54]:
a = np.array([
 [1,2,3],
 [4,5,6]
])

b = np.array([10,20,30])


In [56]:
print(a+b)

[[11 22 33]
 [14 25 36]]


In [57]:
print(b+a)

[[11 22 33]
 [14 25 36]]


In [58]:
import numpy as np
arr = np.array([10,20,30,40,50])

In [59]:
print("Shape:", arr.shape)

Shape: (5,)


In [60]:
print("First:", arr[0])

First: 10


In [61]:
print("Slice:", arr[1:4])

Slice: [20 30 40]


In [62]:
print("Broadcast:", arr + 100)

Broadcast: [110 120 130 140 150]


In [63]:
matrix = np.array([
 [1,2,3],
 [4,5,6],
 [7,8,9]
])

In [64]:
print(matrix.shape)

(3, 3)


In [65]:
print(matrix[:,0])

[1 4 7]


In [66]:
print(matrix[1,:])

[4 5 6]


In [67]:
print(matrix + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [69]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [70]:
 np.dot(a,b)

np.int64(32)

In [71]:
print(np.dot(a,b))

32


In [ ]:
## Multiply corresponding elements:

1×4
2×5
3×6

Result:

4 + 10 + 18

Answer:

32

In [73]:
# Part 5: Matrix Multiplication

In [74]:
# Input Matrix
x = [
    [1,2],
    [3,4]
]

In [75]:
# Weight Matrix
w = [
    [5,6],
    [7,8]
]

In [77]:
# operation : x@w
# or
np.matmul(x,w)

array([[19, 22],
       [43, 50]])

In [ ]:
What Happened?

Row from first matrix

×

Column from second matrix

↓

Dot Product

This is the key.

Matrix multiplication is basically:

Many Dot Products

performed simultaneously.

In [ ]:
1*5+2*7 , 1*6+2*8
3*5+4*7 , 3*6+4*8 

5+14, 6+16
15+28, 18+32

# o/p
[[19, 22],
 [43, 50]]

In [79]:
X = np.array([
    [1,2],
    [3,4]
])

W = np.array([
    [5,6],
    [7,8]
])

print(X @ W)

[[19 22]
 [43 50]]


In [80]:
print(X.shape)
print(W.shape)

(2, 2)
(2, 2)
